// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiK8avyG-DLsReNF96mJoiEIBnFx9ymY',
    appId: '1:506754018325:web:aef6c73037da7eaf0f321c',
    messagingSenderId: '506754018325',
    projectId: 'weather-9c65d',
    authDomain: 'weather-9c65d.firebaseapp.com',
    storageBucket: 'weather-9c65d.firebasestorage.app',
    measurementId: 'G-NYN8783L60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOEDoPcjRcu9xzY7jlNaMXDs090sfkOA',
    appId: '1:506754018325:android:8b4a16125be4d7820f321c',
    messagingSenderId: '506754018325',
    projectId: 'weather-9c65d',
    storageBucket: 'weather-9c65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLAbJy7y3-4onVUeNL5yXZr7T5gllgueA',
    appId: '1:506754018325:ios:d1a28dbab187121e0f321c',
    messagingSenderId: '506754018325',
    projectId: 'weather-9c65d',
    storageBucket: 'weather-9c65d.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLAbJy7y3-4onVUeNL5yXZr7T5gllgueA',
    appId: '1:506754018325:ios:d1a28dbab187121e0f321c',
    messagingSenderId: '506754018325',
    projectId: 'weather-9c65d',
    storageBucket: 'weather-9c65d.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhiK8avyG-DLsReNF96mJoiEIBnFx9ymY',
    appId: '1:506754018325:web:df780820aedbd8d50f321c',
    messagingSenderId: '506754018325',
    projectId: 'weather-9c65d',
    authDomain: 'weather-9c65d.firebaseapp.com',
    storageBucket: 'weather-9c65d.firebasestorage.app',
    measurementId: 'G-CNS0ZGZ9XP',
  );
}
